language: ruby
rvm:
  - 2.4.1

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./bin/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

after_success: cp ./CNAME _site/

deploy:
  # Utiliser le processus de déploiement des pages Github
  provider: pages
  skip-cleanup: true
  # Répertoire où se trouvent les fichiers générés
  local_dir: _site
  # Github security/auth token
  github-token: $GH_TOKEN
  # Conserve les anciens fichiers/constructions des déploiements précédents
  keep-history: true
  # La branche Git sur laquelle on souhaite déployer (master, gh-pages, foo...)
  target_branch: master
  on:
    # Quelle branche déclenchera le déploiement
    branch: source
